[package]
name = "shufflerouter"
version = "1.2.0"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2018"
description = "A suffling router for the Redes de Ordenadores subject"

[dependencies]
structopt = "0.3"
stderrlog = "0.4"
log = "0.4"
mio = "0.6"
rand = { version = "0.7", features = ["log"] }
signal-hook = { version = "0.1", features = ["mio-support"] }
num-format = { version = "0.4", features = ["with-system-locale"] }
