[package]
name = "shufflerouter"
version = "1.5.4"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2018"
description = "A shuffling router for the Redes de Ordenadores subject"

[dependencies]
stderrlog = "0.5"
log = "0.4"
mio = { version = "0.7.7", features = ["os-poll", "net"] }
mio-signals = "0.1"
rand = { version = "0.8", features = ["log"] }
num-format = { version = "0.4", features = ["with-system-locale"] }
thiserror = "1.0.23"
nom = "6.1.2"
anyhow = "1.0"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["wrap_help"]
