[package]
name = "shufflerouter"
version = "1.3.1"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2018"
description = "A shuffling router for the Redes de Ordenadores subject"

[dependencies]
stderrlog = "0.4"
log = "0.4"
mio = { version = "0.7", features = ["os-poll", "udp"] }
mio-signals = "0.1"
rand = { version = "0.7", features = ["log"] }
num-format = { version = "0.4", features = ["with-system-locale"] }

[dependencies.clap]
version = "3.0.0-beta.1"
features = ["wrap_help"]
